name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build ship
      run: "{ echo 'ship'; echo 'Koa'; echo 'React'; } | bash <(curl -s https://raw.githubusercontent.com/paralect/ship-merge/master/ship-merge.sh)"
          
    - name: Commit files
      run: |
        echo 111
        cd ship
        ls
        git init
        git remote add origin https://github.com/Oigen43/ga-test.git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes"

    - name: echooo
      run: echo 2

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
        force: true
        directory: 'ship'
        branch: 'main'
        repository: 'Oigen43/ga-test'
